### ISSUE TITLE
User registration error

### ISSUE THREAD

**Issue by vital-edu** [EspelhoPolitico/espelho-politico#135]
When I try to register a new user the app returns the error:
```
ArgumentError in Devise::RegistrationsController#create
SMTP-AUTH requested but missing secret phrase
```

![selection_001](https://cloud.githubusercontent.com/assets/5282301/13934931/6f8c5134-ef93-11e5-9ad0-fd4819cd312e.png)

**Comment by chocoelho** [comment]
I think that there's something wrong with our SMTP configuration. There 
must be some instructions on how to set up email configuration.

**Comment by vital-edu** [comment]
I already know the solution:
Change the config.action_mailer.delivery_method from :smtp to :file

But I am trying to format the EMAIL properly, because it is stored in tmp/mails with wrong encoding, what unable to read the activation code properly.
